### ISSUE TITLE
无法完成弹窗计时任务

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task#32]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

所有需要跳转网页计时的观看任务全部都无法完成。似乎是因为并没能弹出新页面/将任务页面状态置为后台。

### 关于哪一个网站

https://gleam.io/V368O/hidden-old-house-topdown-3d-steam-key

### 浏览器版本

```json
Google Chrome	129.0.6668.90
```

### 脚本管理器版本

TM 5.3.0

### 脚本版本

4.4.12

### 错误信息

```shell
main-bundle.js:2 Uncaught Error: Extension context invalidated.
    at Bi (main-bundle.js:2:201457)
    at t.value (main-bundle.js:2:402667)
    at id (main-bundle.js:2:409403)
    at HTMLDocument.Ju (main-bundle.js:2:308720)
    at HTMLDocument.r (main-bundle.js:2:158279)
22:22:21.427 w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:71 Error: another entry is happening
    at attemptEntry (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:79:22608)
    at $scope.enterLinkClick (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:79:18972)
    at fn (eval at compile (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:74:27064), <anonymous>:4:258)
    at callback (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:75:25261)
    at Scope.$eval (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72:7081)
    at Scope.$apply (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72:7412)
    at HTMLAnchorElement.<anonymous> (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:75:25368)
    at HTMLAnchorElement.dispatch (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13:12076)
    at elemData.handle (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13:8870)
    at Gleam.verifyTask (userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:9527:25) 'Possibly unhandled rejection: {}'
（匿名） @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:71
（匿名） @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:70
processChecks @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:71
$digest @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72
$apply @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72
（匿名） @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:75
dispatch @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13
elemData.handle @ w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13
verifyTask @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:9527
await in verifyTask
（匿名） @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10795
dispatch @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:3
v.handle @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:3
22:22:25.975 w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:71 Error: another entry is happening
    at attemptEntry (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:79:22608)
    at $scope.enterLinkClick (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:79:18972)
    at fn (eval at compile (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:74:27064), <anonymous>:4:258)
    at callback (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:75:25261)
    at Scope.$eval (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72:7081)
    at Scope.$apply (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:72:7412)
    at HTMLAnchorElement.<anonymous> (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:75:25368)
    at HTMLAnchorElement.dispatch (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13:12076)
    at elemData.handle (w-ee638232b140b74c4107f6c31cebaa625018718c0de14ea5e179e31716820a7d.js:13:8870)
    at Gleam.verifyTask (userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:9527:25) 'Possibly unhandled rejection: {}'
```

### 执行日志

```auto
正在获取并处理任务信息...Success
正在加入Steam组[gamesforfarm]...Success
所有任务已完成！
正在验证任务...
已尝试验证所有任务，验证失败的任务请尝试手动验证或完成！
```

### 附加截图

![image](https://github.com/user-attachments/assets/edb28629-18fb-4375-9516-7ef09caa2ba2)

**Comment by HCLonely** [comment]
验证的时候动一下鼠标

**Comment by Mishasama** [comment]
就是说以后遇到这种任务只要一直动鼠标就好了？

**Comment by HCLonely** [comment]
> 就是说以后遇到这种任务只要一直动鼠标就好了？

是的，目前还没有其他的办法解决

**Comment by Mishasama** [comment]
哦，下次我再试试。
